---
- name: Grub changes
  hosts: example
  become: yes
  tasks:

    - name: insert into /etc/default/grub
      lineinfile:
        backrefs: true
        path: /etc/default/grub
        regexp: "^(GRUB_CMDLINE_LINUX=\".*)\"$"
        line: '\1 net.ifnames=0 biosdevname=0"'
      notify: Grub Update

  handlers:
    - name: Grub Update
      command: update-grub