---
# tasks file for httpd
- name: Install Firewalld if not installed
  yum:
    name: firewalld
    state: latest

- name: Start service firewalld, if not started
  service:
    name: firewalld
    state: started
    enabled: yes

- name: permit traffic in default zone for http/https services
  ansible.posix.firewalld:
    permanent: yes
    immediate: yes
    service: "{{ item }}"
    state: enabled
  with_items:
    - http
    - https

- name: Install httpd package
  yum:
    name: httpd
    state: latest

- name: Start service httpd, if not yet and enabled
  service:
    name: httpd
    state: started
    enabled: yes

- name: stat http welcome.conf
  stat:
    path: /etc/httpd/conf.d/welcome.conf
  register: welcome

- name: Move welcome.conf to welcome.conf.backup
  command: mv /etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/welcome.conf.backup
  when: welcome.stat.exists
  notify: Restart httpd

- name: Template /var/www/html/index.html
  template:
    dest: index.html.j2
    src: var/www/html/index.html
  notify: Restart httpd

- name: Create a file with content /var/www/html/index.html
  copy:
    dest: "/var/www/html/index.html"
    content: |
      <h1> Welcome to my web server, EPAMer! </h1>
  notify: Restart httpd